from pathlib import Path

root = Path('/home/ubuntu/work/webforge')
index = root / 'index.html'
text = index.read_text()
old_showcase = '<div class="demoGrid"><a class="demo restaurant" href="/demos/restaurantdesign.html">'
new_showcase = '''<div class="filterBar" role="group" aria-label="Filter portfolio demos"><span class="filterLabel">FILTER BY INDUSTRY</span><button class="filterBtn active" data-filter="all">All work</button><button class="filterBtn" data-filter="business">Business</button><button class="filterBtn" data-filter="lifestyle">Lifestyle</button><button class="filterBtn" data-filter="culture">Culture</button><button class="filterBtn" data-filter="new">New directions</button></div><div class="demoGrid"><a class="demo restaurant" data-category="lifestyle" href="/demos/restaurantdesign.html">'''
text = text.replace(old_showcase, new_showcase)
replacements = {
'<a class="demo school" href="/demos/schooldesign.html">':'<a class="demo school" data-category="culture" href="/demos/schooldesign.html">',
'<a class="demo business" href="/demos/businessdesign.html">':'<a class="demo business" data-category="business" href="/demos/businessdesign.html">',
'<a class="demo creator" href="/demos/creatordesign.html">':'<a class="demo creator" data-category="lifestyle" href="/demos/creatordesign.html">',
'<a class="demo event" href="/demos/eventdesign.html">':'<a class="demo event" data-category="culture" href="/demos/eventdesign.html">',
'<a class="demo beauty" href="/demos/beautydesign.html">':'<a class="demo beauty" data-category="lifestyle" href="/demos/beautydesign.html">',
'<a class="demo realestate" href="/demos/realestatedesign.html">':'<a class="demo realestate" data-category="business" href="/demos/realestatedesign.html">',
'<a class="demo fitness" href="/demos/fitnessdesign.html">':'<a class="demo fitness" data-category="lifestyle" href="/demos/fitnessdesign.html">',
'<a class="demo tech" href="/demos/techdesign.html">':'<a class="demo tech" data-category="business" href="/demos/techdesign.html">',
}
for a,b in replacements.items(): text=text.replace(a,b)
needle = '</section>\n<section id="pricing" class="section">'
testimonials = '''</section>
<section class="section testimonials" aria-labelledby="testimonial-title"><div class="sectionHead"><div><p class="eyebrow">CLIENT NOTES</p><h2 id="testimonial-title">Good work gets <span>talked about.</span></h2></div><div class="sliderControls"><button class="sliderBtn" id="testimonialPrev" aria-label="Previous testimonial">←</button><button class="sliderBtn" id="testimonialNext" aria-label="Next testimonial">→</button></div></div><div class="testimonialViewport"><div class="testimonialTrack" id="testimonialTrack"><article class="testimonial"><div class="quoteMark">“</div><blockquote>WebForge took our complicated offer and made it feel obvious. We started getting better enquiries within the first week.</blockquote><div class="person"><span class="avatar">AO</span><span><b>Amara Okafor</b><small>Founder, Luma Advisory</small></span></div></article><article class="testimonial"><div class="quoteMark">“</div><blockquote>The new site finally feels like the quality of the experience we deliver in person. It is clear, warm and very easy to book.</blockquote><div class="person"><span class="avatar">DK</span><span><b>Daniel Kalu</b><small>Director, Maison Table</small></span></div></article><article class="testimonial"><div class="quoteMark">“</div><blockquote>What stood out was the thinking. Every section had a purpose, and the result gave our team confidence to share the brand.</blockquote><div class="person"><span class="avatar">MS</span><span><b>Maya Singh</b><small>Creative Lead, Northstar</small></span></div></article></div></div><div class="sliderDots" id="sliderDots" aria-label="Testimonial slides"><button class="dot active" aria-label="Show testimonial 1"></button><button class="dot" aria-label="Show testimonial 2"></button><button class="dot" aria-label="Show testimonial 3"></button></div></section>
<section id="pricing" class="section">'''
text = text.replace(needle, testimonials)
text = text.replace('SHOWCASE · 09 DIRECTIONS','SHOWCASE · 12 DIRECTIONS')
text = text.replace('<span>09</span><small>Industry demos</small>','<span>12</span><small>Industry demos</small>')
index.write_text(text)

css = root / 'style.css'
styles = css.read_text()
styles += '''\n.filterBar{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:-10px auto 28px;max-width:1400px;padding:0 6%}.filterLabel{font-size:9px;letter-spacing:2px;color:#667386;margin-right:7px}.filterBtn,.sliderBtn{border:1px solid #293646;background:#0c121b;color:#aeb9c8;border-radius:999px;padding:9px 13px;font:600 12px inherit;cursor:pointer;transition:.2s}.filterBtn:hover,.filterBtn.active{background:#fff;color:#090b10;border-color:#fff}.demo.is-hidden{display:none}.sliderControls{display:flex;gap:8px}.sliderBtn{width:42px;height:42px;padding:0;font-size:18px}.sliderBtn:hover{border-color:#8e80ff;color:#fff}.testimonials{border-top:1px solid var(--line)}.testimonialViewport{overflow:hidden}.testimonialTrack{display:flex;transition:transform .45s var(--ease)}.testimonial{min-width:100%;display:grid;grid-template-columns:120px 1fr 230px;gap:30px;align-items:start;padding:42px 44px;background:linear-gradient(110deg,#101727,#0b1019);border:1px solid var(--line);border-radius:22px}.quoteMark{font:700 90px/.7 Georgia;color:#8b7eff}.testimonial blockquote{font:500 clamp(24px,3vw,38px)/1.18 "Space Grotesk";letter-spacing:-1px;margin:0;max-width:780px}.person{display:flex;align-items:center;gap:12px;margin-top:8px}.avatar{width:42px;height:42px;display:grid;place-items:center;border-radius:50%;background:linear-gradient(135deg,#8b7eff,#54dfff);color:#080a0e;font:700 12px "Space Grotesk"}.person span:last-child{display:grid;gap:4px}.person b{font-size:13px}.person small{font-size:11px;color:#78869a}.sliderDots{display:flex;justify-content:center;gap:7px;margin-top:18px}.dot{width:7px;height:7px;padding:0;border:0;border-radius:50%;background:#354154;cursor:pointer}.dot.active{width:24px;border-radius:8px;background:#8e80ff}@media(max-width:800px){.testimonial{grid-template-columns:1fr;gap:12px;padding:30px}.quoteMark{font-size:64px}.person{margin-top:12px}.filterBar{padding:0 0}}\n'''
css.write_text(styles)

script = root / 'script.js'
js = script.read_text()
js += '''\nconst filterButtons = document.querySelectorAll('.filterBtn');\nconst portfolioCards = document.querySelectorAll('.demoGrid .demo');\nfilterButtons.forEach((button) => button.addEventListener('click', () => {\n  const filter = button.dataset.filter;\n  filterButtons.forEach((item) => item.classList.toggle('active', item === button));\n  portfolioCards.forEach((card) => {\n    const visible = filter === 'all' || card.dataset.category === filter;\n    card.classList.toggle('is-hidden', !visible);\n  });\n}));\n\nconst track = document.getElementById('testimonialTrack');\nconst dots = [...document.querySelectorAll('.dot')];\nlet testimonialIndex = 0;\nconst showTestimonial = (index) => {\n  if (!track) return;\n  testimonialIndex = (index + dots.length) % dots.length;\n  track.style.transform = `translateX(-${testimonialIndex * 100}%)`;\n  dots.forEach((dot, dotIndex) => dot.classList.toggle('active', dotIndex === testimonialIndex));\n};\ndocument.getElementById('testimonialPrev')?.addEventListener('click', () => showTestimonial(testimonialIndex - 1));\ndocument.getElementById('testimonialNext')?.addEventListener('click', () => showTestimonial(testimonialIndex + 1));\ndots.forEach((dot, index) => dot.addEventListener('click', () => showTestimonial(index)));\nlet testimonialTimer = window.setInterval(() => showTestimonial(testimonialIndex + 1), 6500);\n[...document.querySelectorAll('.sliderBtn, .dot')].forEach((control) => control.addEventListener('click', () => { window.clearInterval(testimonialTimer); testimonialTimer = window.setInterval(() => showTestimonial(testimonialIndex + 1), 6500); }));\n'''
script.write_text(js)
